### ISSUE TITLE
Error when running train

### ISSUE THREAD

**Issue by christopherandrade554** [Qerim-iseni09/Stock-Predictor-V4#2]
![Capture](https://github.com/Qerim-iseni09/Stock-Predictor-V4/assets/91700638/e5933cb9-142f-4442-8805-defdb15276bc)

**Comment by lex-hue** [comment]
It appears that the Python version you have is older than the one I used (Python 3.10.4) to test the entire script. Currently, I have only tested the repository on Linux, but I plan to make it compatible with other operating systems as well. I suspect that you may have skipped the installation process and jumped straight into using train.py without preprocessing the data. To preprocess the data, you will need to install talib on your computer. Once you have installed talib, try preprocessing the data and then training it again.
