### ISSUE TITLE
Training on each stock

### ISSUE THREAD

**Issue by SamuelLachance** [Qerim-iseni09/Stock-Predictor-V4#4]
when i put like 80 different stocks and prepare the data , it only take the mean. I think the model would be more efficient if we could train it on every stock that we want and not only on One or the Mean . 

sorry if my english is bad . BTW good job with this project . keep going !

**Comment by lex-hue** [comment]
I don't have much expertise in that particular area, and I'm unsure if I can successfully complete the task. However, I'm willing to give it a try...

Alternatively, you could submit a pull request or something similar. I would greatly appreciate it.

**Comment by lex-hue** [comment]
After conducting a thorough investigation, I have determined that I am unable to accomplish this task. Therefore, I am seeking assistance from someone who can help me with it.
