### ISSUE TITLE
Issue running with --eval

### ISSUE THREAD

**Issue by 0xMimir** [Qerim-iseni09/Stock-Predictor-V4#6]
**Describe the bug**
Error getting model eval

**To Reproduce**
```sh
git clone https://github.com/Qerim-iseni09/Stock-Predictor-V4.git
cd Stock-Predictor-V4
python SPV4.py --install
python SPV4.py --prepare_data
python SPV4.py --train
python SPV4.py --eval
```

**Expected behavior**
In README.md is says it should print out the root mean squared error (RMSE), the MAPE and Total Rewards will be plotted

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] linux
 - Browser [e.g. chrome, safari] Brave (don't see why this matters'
 - Version [e.g. 22] 3.11.4

**Comment by lex-hue** [comment]
Hello there!

The Evaluation feature has been taken out in this moment as it had some problems, you can skip the Evaluation Process as its in Work. I Forgot to write in the Readme that its in the works. Please wait until the Evaluation Logic comes back. 
Thank you for your Support and Reading.
